import type { User, Task, LeaderboardEntry, Reward, Student, Class, PerformanceData, Notification, Message, Conversation, Quiz, QuizAttempt, AppNotification, Team, StudyGroup, VideoLesson, VideoProgress, Playlist, Note, Tournament, PeerReview, Flashcard, FlashcardDeck, WeakArea, LearningPath, AIInsight, AIPrediction, AIRiskAlert, AIRecommendation } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Alice Teacher',
    email: 'alice@school.com',
    role: 'TEACHER',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
  },
  {
    id: 'u2',
    name: 'Bob Admin',
    email: 'admin@school.com',
    role: 'ADMIN',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
  },
  {
    id: 'u3',
    name: 'Sarah Johnson',
    email: 'sarah@school.com',
    role: 'TEACHER',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  },
  {
    id: 'u4',
    name: 'Michael Chen',
    email: 'michael@school.com',
    role: 'TEACHER',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
  },
  {
    id: 's1',
    name: 'Charlie Student',
    email: 'charlie@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie',
    grade: '10',
    section: 'A',
    xp: 1250,
    wallet: 300,
  } as Student,
  {
    id: 's2',
    name: 'Diana Prince',
    email: 'diana@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diana',
    grade: '10',
    section: 'A',
    xp: 1200,
    wallet: 250,
  } as Student,
  {
    id: 's3',
    name: 'Clark Kent',
    email: 'clark@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Clark',
    grade: '10',
    section: 'B',
    xp: 1150,
    wallet: 200,
  } as Student,
  {
    id: 's4',
    name: 'Bruce Wayne',
    email: 'bruce@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bruce',
    grade: '10',
    section: 'A',
    xp: 1100,
    wallet: 180,
  } as Student,
  {
    id: 's5',
    name: 'Peter Parker',
    email: 'peter@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Peter',
    grade: '9',
    section: 'A',
    xp: 1050,
    wallet: 150,
  } as Student,
  {
    id: 's6',
    name: 'Emma Watson',
    email: 'emma@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    grade: '10',
    section: 'B',
    xp: 1020,
    wallet: 140,
  } as Student,
  {
    id: 's7',
    name: 'James Bond',
    email: 'james@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    grade: '9',
    section: 'B',
    xp: 980,
    wallet: 120,
  } as Student,
  {
    id: 's8',
    name: 'Natasha Romanoff',
    email: 'natasha@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Natasha',
    grade: '10',
    section: 'A',
    xp: 950,
    wallet: 110,
  } as Student,
  {
    id: 'p1',
    name: 'David Parent',
    email: 'david@parent.com',
    role: 'PARENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
  },
  {
    id: 'p2',
    name: 'Maria Garcia',
    email: 'maria@parent.com',
    role: 'PARENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
  },
];

export const MOCK_CLASSES: Class[] = [
  { id: 'c1', name: 'Grade 10A', grade: '10', section: 'A', teacherId: 'u1', studentCount: 28 },
  { id: 'c2', name: 'Grade 10B', grade: '10', section: 'B', teacherId: 'u1', studentCount: 25 },
  { id: 'c3', name: 'Grade 9A', grade: '9', section: 'A', teacherId: 'u3', studentCount: 30 },
  { id: 'c4', name: 'Grade 9B', grade: '9', section: 'B', teacherId: 'u3', studentCount: 27 },
  { id: 'c5', name: 'Grade 11A', grade: '11', section: 'A', teacherId: 'u4', studentCount: 32 },
  { id: 'c6', name: 'Grade 11B', grade: '11', section: 'B', teacherId: 'u4', studentCount: 29 },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Algebra Linear Equations',
    description: 'Complete exercises 5.1 to 5.5 in your textbook. Show all work and submit your solutions.',
    subject: 'Math',
    assignedDate: '2023-10-01',
    dueDate: '2023-10-10',
    xpReward: 100,
    status: 'PENDING',
  },
  {
    id: 't2',
    title: 'Physics Lab Report',
    description: 'Submit the lab report for the Pendulum experiment. Include data analysis and conclusions.',
    subject: 'Science',
    assignedDate: '2023-10-02',
    dueDate: '2023-10-09',
    xpReward: 150,
    status: 'SUBMITTED',
    submittedFileUrl: 'http://example.com/report.pdf',
  },
  {
    id: 't3',
    title: 'History Essay',
    description: 'Write an essay on the Industrial Revolution (500-700 words). Include causes, effects, and historical significance.',
    subject: 'History',
    assignedDate: '2023-09-20',
    dueDate: '2023-09-30',
    xpReward: 200,
    status: 'GRADED',
    grade: 'A',
    feedback: 'Excellent work! Well-researched and clearly written.',
  },
  {
    id: 't4',
    title: 'English Poetry Analysis',
    description: 'Analyze the poem "The Road Not Taken" by Robert Frost. Discuss themes, literary devices, and personal interpretation.',
    subject: 'English',
    assignedDate: '2023-10-05',
    dueDate: '2023-10-12',
    xpReward: 120,
    status: 'PENDING',
  },
  {
    id: 't5',
    title: 'Chemistry Periodic Table Quiz',
    description: 'Complete the online quiz on periodic table trends and element properties.',
    subject: 'Science',
    assignedDate: '2023-10-03',
    dueDate: '2023-10-08',
    xpReward: 80,
    status: 'SUBMITTED',
    submittedFileUrl: 'http://example.com/quiz.pdf',
  },
  {
    id: 't6',
    title: 'Geometry Problem Set',
    description: 'Solve problems 1-15 from Chapter 7. Focus on triangle properties and proofs.',
    subject: 'Math',
    assignedDate: '2023-09-25',
    dueDate: '2023-10-05',
    xpReward: 110,
    status: 'GRADED',
    grade: 'B+',
    feedback: 'Good effort! Review triangle congruence theorems.',
  },
  {
    id: 't7',
    title: 'World War II Presentation',
    description: 'Create a 10-slide presentation on a major battle of WWII. Include images and citations.',
    subject: 'History',
    assignedDate: '2023-10-06',
    dueDate: '2023-10-15',
    xpReward: 180,
    status: 'PENDING',
  },
  {
    id: 't8',
    title: 'Biology Cell Structure Lab',
    description: 'Complete the microscope lab worksheet on plant and animal cell structures.',
    subject: 'Science',
    assignedDate: '2023-10-04',
    dueDate: '2023-10-11',
    xpReward: 90,
    status: 'SUBMITTED',
    submittedFileUrl: 'http://example.com/lab.pdf',
  },
  {
    id: 't9',
    title: 'Creative Writing Assignment',
    description: 'Write a short story (1000 words) with a clear plot, setting, and character development.',
    subject: 'English',
    assignedDate: '2023-09-28',
    dueDate: '2023-10-07',
    xpReward: 140,
    status: 'GRADED',
    grade: 'A-',
    feedback: 'Creative and engaging! Work on dialogue formatting.',
  },
  {
    id: 't10',
    title: 'Calculus Derivatives Practice',
    description: 'Complete the derivative practice problems. Show all steps in your solutions.',
    subject: 'Math',
    assignedDate: '2023-10-07',
    dueDate: '2023-10-14',
    xpReward: 130,
    status: 'PENDING',
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, studentId: 's1', studentName: 'Charlie Student', xp: 1250, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie' },
  { rank: 2, studentId: 's2', studentName: 'Diana Prince', xp: 1200, trend: 'SAME', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diana' },
  { rank: 3, studentId: 's3', studentName: 'Clark Kent', xp: 1150, trend: 'DOWN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Clark' },
  { rank: 4, studentId: 's4', studentName: 'Bruce Wayne', xp: 1100, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bruce' },
  { rank: 5, studentId: 's5', studentName: 'Peter Parker', xp: 1050, trend: 'SAME', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Peter' },
  { rank: 6, studentId: 's6', studentName: 'Emma Watson', xp: 1020, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma' },
  { rank: 7, studentId: 's7', studentName: 'James Bond', xp: 980, trend: 'DOWN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James' },
  { rank: 8, studentId: 's8', studentName: 'Natasha Romanoff', xp: 950, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Natasha' },
  { rank: 9, studentId: 's9', studentName: 'Tony Stark', xp: 920, trend: 'SAME', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tony' },
  { rank: 10, studentId: 's10', studentName: 'Steve Rogers', xp: 890, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Steve' },
  { rank: 11, studentId: 's11', studentName: 'Wanda Maximoff', xp: 870, trend: 'DOWN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Wanda' },
  { rank: 12, studentId: 's12', studentName: 'Barry Allen', xp: 850, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Barry' },
  { rank: 13, studentId: 's13', studentName: 'Oliver Queen', xp: 820, trend: 'SAME', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver' },
  { rank: 14, studentId: 's14', studentName: 'Kara Danvers', xp: 800, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kara' },
  { rank: 15, studentId: 's15', studentName: 'John Constantine', xp: 780, trend: 'DOWN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John' },
  { rank: 16, studentId: 's16', studentName: 'Zatanna Zatara', xp: 760, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Zatanna' },
  { rank: 17, studentId: 's17', studentName: 'Arthur Curry', xp: 740, trend: 'SAME', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arthur' },
  { rank: 18, studentId: 's18', studentName: 'Diana Prince', xp: 720, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diana2' },
  { rank: 19, studentId: 's19', studentName: 'Hal Jordan', xp: 700, trend: 'DOWN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hal' },
  { rank: 20, studentId: 's20', studentName: 'Jessica Cruz', xp: 680, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica' },
];

export const MOCK_REWARDS: Reward[] = [
  { id: 'r1', name: 'Homework Pass', cost: 500, type: 'PRIVILEGE' },
  { id: 'r2', name: 'Extra 5 mins Break', cost: 200, type: 'PRIVILEGE' },
  { id: 'r3', name: 'Fancy Pen', cost: 1000, type: 'ITEM' },
  { id: 'r4', name: 'Lunch with Teacher', cost: 800, type: 'PRIVILEGE' },
  { id: 'r5', name: 'Custom Notebook', cost: 600, type: 'ITEM' },
  { id: 'r6', name: 'Skip One Quiz', cost: 400, type: 'PRIVILEGE' },
  { id: 'r7', name: 'School Merchandise', cost: 1200, type: 'ITEM' },
  { id: 'r8', name: 'Extra Credit Opportunity', cost: 300, type: 'PRIVILEGE' },
  { id: 'r9', name: 'Gift Card ($10)', cost: 1500, type: 'ITEM' },
  { id: 'r10', name: 'Choose Your Seat', cost: 250, type: 'PRIVILEGE' },
];

export const MOCK_PERFORMANCE: PerformanceData[] = [
  // Math
  { subject: 'Math', score: 95, date: '2023-09-01', xpEarned: 100 },
  { subject: 'Math', score: 92, date: '2023-09-15', xpEarned: 95 },
  { subject: 'Math', score: 98, date: '2023-10-01', xpEarned: 105 },
  { subject: 'Math', score: 94, date: '2023-10-15', xpEarned: 100 },
  { subject: 'Math', score: 96, date: '2023-11-01', xpEarned: 102 },
  // Science
  { subject: 'Science', score: 88, date: '2023-09-05', xpEarned: 90 },
  { subject: 'Science', score: 90, date: '2023-09-20', xpEarned: 92 },
  { subject: 'Science', score: 93, date: '2023-10-05', xpEarned: 95 },
  { subject: 'Science', score: 91, date: '2023-10-20', xpEarned: 93 },
  { subject: 'Science', score: 95, date: '2023-11-05', xpEarned: 98 },
  // History
  { subject: 'History', score: 85, date: '2023-09-10', xpEarned: 85 },
  { subject: 'History', score: 90, date: '2023-09-25', xpEarned: 90 },
  { subject: 'History', score: 87, date: '2023-10-10', xpEarned: 87 },
  { subject: 'History', score: 92, date: '2023-10-25', xpEarned: 92 },
  // English
  { subject: 'English', score: 89, date: '2023-09-08', xpEarned: 89 },
  { subject: 'English', score: 91, date: '2023-09-22', xpEarned: 91 },
  { subject: 'English', score: 88, date: '2023-10-08', xpEarned: 88 },
  { subject: 'English', score: 93, date: '2023-10-22', xpEarned: 93 },
  { subject: 'English', score: 90, date: '2023-11-08', xpEarned: 90 },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', title: 'New Task Assigned', message: 'You have a new Math assignment due tomorrow', type: 'INFO', read: false, timestamp: '2023-10-08T10:00:00Z' },
  { id: 'n2', title: 'Task Graded', message: 'Your History essay has been graded: A', type: 'SUCCESS', read: false, timestamp: '2023-10-07T14:30:00Z' },
  { id: 'n3', title: 'XP Earned', message: 'You earned 150 XP for completing Physics Lab', type: 'SUCCESS', read: true, timestamp: '2023-10-06T09:15:00Z' },
  { id: 'n4', title: 'Leaderboard Update', message: 'You moved up to #1 position!', type: 'SUCCESS', read: false, timestamp: '2023-10-05T16:45:00Z' },
  { id: 'n5', title: 'Reward Available', message: 'New reward "Homework Pass" is now available in the store', type: 'INFO', read: false, timestamp: '2023-10-04T11:20:00Z' },
  { id: 'n6', title: 'Task Reminder', message: 'Your English assignment is due in 2 days', type: 'WARNING', read: true, timestamp: '2023-10-03T08:30:00Z' },
  { id: 'n7', title: 'Achievement Unlocked', message: 'Congratulations! You completed 10 tasks this month', type: 'SUCCESS', read: true, timestamp: '2023-10-02T15:00:00Z' },
  { id: 'n8', title: 'Task Graded', message: 'Your Math quiz has been graded: B+', type: 'SUCCESS', read: false, timestamp: '2023-10-01T12:00:00Z' },
  { id: 'n9', title: 'XP Milestone', message: 'You reached 1000 XP! Level up!', type: 'SUCCESS', read: true, timestamp: '2023-09-30T10:00:00Z' },
  { id: 'n10', title: 'New Task Assigned', message: 'Chemistry lab report due next week', type: 'INFO', read: false, timestamp: '2023-09-29T14:15:00Z' },
];

// Messaging System Mock Data
export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv1',
    type: 'DIRECT',
    participants: ['u5', 'u1'],
    unreadCount: 2,
    lastMessage: {
      id: 'msg1',
      conversationId: 'conv1',
      senderId: 'u1',
      senderName: 'Alice Teacher',
      content: 'Great work on the assignment!',
      timestamp: '2023-10-08T14:30:00Z',
      read: false,
    },
    createdAt: '2023-10-01T10:00:00Z',
  },
  {
    id: 'conv2',
    type: 'GROUP',
    name: 'Math Study Group',
    participants: ['u5', 'u6', 'u7', 'u8'],
    unreadCount: 5,
    lastMessage: {
      id: 'msg2',
      conversationId: 'conv2',
      senderId: 'u6',
      senderName: 'Emma Wilson',
      content: 'Can someone help with problem 5?',
      timestamp: '2023-10-08T15:00:00Z',
      read: false,
    },
    createdAt: '2023-09-15T09:00:00Z',
  },
  {
    id: 'conv3',
    type: 'CLASS',
    name: 'Grade 10 - Section A',
    participants: ['u1', 'u5', 'u6', 'u7', 'u8', 'u9'],
    unreadCount: 0,
    lastMessage: {
      id: 'msg3',
      conversationId: 'conv3',
      senderId: 'u1',
      senderName: 'Alice Teacher',
      content: 'Reminder: Quiz tomorrow at 9 AM',
      timestamp: '2023-10-08T10:00:00Z',
      read: true,
    },
    createdAt: '2023-09-01T08:00:00Z',
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  conv1: [
    {
      id: 'msg1',
      conversationId: 'conv1',
      senderId: 'u1',
      senderName: 'Alice Teacher',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
      content: 'Great work on the assignment!',
      timestamp: '2023-10-08T14:30:00Z',
      read: false,
    },
    {
      id: 'msg2',
      conversationId: 'conv1',
      senderId: 'u5',
      senderName: 'Charlie Brown',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie',
      content: 'Thank you! I really enjoyed working on it.',
      timestamp: '2023-10-08T14:25:00Z',
      read: true,
    },
  ],
  conv2: [
    {
      id: 'msg3',
      conversationId: 'conv2',
      senderId: 'u6',
      senderName: 'Emma Wilson',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
      content: 'Can someone help with problem 5?',
      timestamp: '2023-10-08T15:00:00Z',
      read: false,
    },
    {
      id: 'msg4',
      conversationId: 'conv2',
      senderId: 'u5',
      senderName: 'Charlie Brown',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie',
      content: 'Sure! I can help. What part are you stuck on?',
      timestamp: '2023-10-08T14:45:00Z',
      read: true,
    },
  ],
};

// Interactive Quizzes Mock Data
export const MOCK_QUIZZES: Quiz[] = [
  {
    id: 'quiz1',
    title: 'Math Fundamentals Quiz',
    description: 'Test your understanding of basic algebra and geometry',
    subject: 'Math',
    createdBy: 'u1',
    createdAt: '2023-10-01T10:00:00Z',
    timeLimit: 30,
    totalQuestions: 10,
    totalPoints: 100,
    attempts: 0,
    maxAttempts: 3,
    questions: [
      {
        id: 'q1',
        type: 'MULTIPLE_CHOICE',
        question: 'What is 2x + 5 = 15?',
        options: ['x = 5', 'x = 10', 'x = 7.5', 'x = 20'],
        correctAnswer: 'x = 5',
        points: 10,
        explanation: 'Subtract 5 from both sides: 2x = 10, then divide by 2: x = 5',
      },
      {
        id: 'q2',
        type: 'TRUE_FALSE',
        question: 'A triangle always has three sides.',
        options: ['True', 'False'],
        correctAnswer: 'True',
        points: 10,
        explanation: 'By definition, a triangle is a polygon with exactly three sides.',
      },
    ],
    status: 'ACTIVE',
    dueDate: '2023-10-15T23:59:59Z',
  },
  {
    id: 'quiz2',
    title: 'Science Quiz: Photosynthesis',
    description: 'Test your knowledge about plant biology',
    subject: 'Science',
    createdBy: 'u3',
    createdAt: '2023-10-05T09:00:00Z',
    timeLimit: 20,
    totalQuestions: 8,
    totalPoints: 80,
    attempts: 1,
    maxAttempts: 2,
    questions: [
      {
        id: 'q3',
        type: 'MULTIPLE_CHOICE',
        question: 'What is the primary product of photosynthesis?',
        options: ['Oxygen', 'Glucose', 'Carbon Dioxide', 'Water'],
        correctAnswer: 'Glucose',
        points: 10,
        explanation: 'Glucose (C6H12O6) is the primary product, while oxygen is a byproduct.',
      },
    ],
    status: 'ACTIVE',
    dueDate: '2023-10-20T23:59:59Z',
  },
];

// Notification Center Mock Data
export const MOCK_APP_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'an1',
    userId: 'u5',
    type: 'TASK',
    title: 'New Task Assigned',
    message: 'Math assignment "Quadratic Equations" is due in 2 days',
    read: false,
    timestamp: '2023-10-08T10:00:00Z',
    actionUrl: '/tasks',
    icon: '📝',
    priority: 'HIGH',
  },
  {
    id: 'an2',
    userId: 'u5',
    type: 'GRADE',
    title: 'Assignment Graded',
    message: 'Your History essay received an A grade!',
    read: false,
    timestamp: '2023-10-08T09:30:00Z',
    actionUrl: '/tasks',
    icon: '🎉',
    priority: 'MEDIUM',
  },
  {
    id: 'an3',
    userId: 'u5',
    type: 'MESSAGE',
    title: 'New Message',
    message: 'Alice Teacher sent you a message',
    read: false,
    timestamp: '2023-10-08T08:15:00Z',
    actionUrl: '/messages',
    icon: '💬',
    priority: 'MEDIUM',
  },
  {
    id: 'an4',
    userId: 'u5',
    type: 'ACHIEVEMENT',
    title: 'Badge Unlocked',
    message: 'You earned the "Math Wizard" badge!',
    read: true,
    timestamp: '2023-10-07T16:00:00Z',
    actionUrl: '/badges',
    icon: '🏆',
    priority: 'LOW',
  },
  {
    id: 'an5',
    userId: 'u5',
    type: 'ANNOUNCEMENT',
    title: 'School Holiday',
    message: 'School will be closed on October 15th for Diwali',
    read: false,
    timestamp: '2023-10-07T12:00:00Z',
    actionUrl: '/announcements',
    icon: '📢',
    priority: 'HIGH',
  },
];

// Teams/Clans Mock Data
export const MOCK_TEAMS: Team[] = [
  {
    id: 'team1',
    name: 'Math Masters',
    description: 'A team dedicated to excelling in mathematics',
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=MathMasters',
    leaderId: 'u5',
    leaderName: 'Charlie Brown',
    members: [
      { userId: 'u5', userName: 'Charlie Brown', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie', role: 'LEADER', joinedAt: '2023-09-01T10:00:00Z', contributionXP: 1250 },
      { userId: 'u6', userName: 'Emma Wilson', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma', role: 'MEMBER', joinedAt: '2023-09-05T14:00:00Z', contributionXP: 980 },
      { userId: 'u7', userName: 'David Lee', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David', role: 'MEMBER', joinedAt: '2023-09-10T09:00:00Z', contributionXP: 1100 },
    ],
    totalXP: 3330,
    rank: 1,
    createdAt: '2023-09-01T10:00:00Z',
    achievements: ['b2', 'b8'],
    stats: {
      totalTasksCompleted: 45,
      averageScore: 92,
      activeMembers: 3,
    },
  },
  {
    id: 'team2',
    name: 'Science Squad',
    description: 'Exploring the wonders of science together',
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=ScienceSquad',
    leaderId: 'u8',
    leaderName: 'Olivia Martinez',
    members: [
      { userId: 'u8', userName: 'Olivia Martinez', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia', role: 'LEADER', joinedAt: '2023-09-02T11:00:00Z', contributionXP: 1050 },
      { userId: 'u9', userName: 'James Taylor', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James', role: 'MEMBER', joinedAt: '2023-09-03T15:00:00Z', contributionXP: 890 },
    ],
    totalXP: 1940,
    rank: 2,
    createdAt: '2023-09-02T11:00:00Z',
    achievements: ['b3'],
    stats: {
      totalTasksCompleted: 32,
      averageScore: 88,
      activeMembers: 2,
    },
  },
];

// Phase 2 Mock Data - Study Groups
export const MOCK_STUDY_GROUPS: StudyGroup[] = [
  {
    id: 'sg1',
    name: 'Math Study Group',
    description: 'Collaborative learning for advanced mathematics',
    subject: 'Math',
    createdBy: 'u5',
    createdAt: '2023-09-15T10:00:00Z',
    members: [
      { userId: 'u5', userName: 'Charlie Brown', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie', role: 'CREATOR', joinedAt: '2023-09-15T10:00:00Z', contributionXP: 500 },
      { userId: 'u6', userName: 'Emma Wilson', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma', role: 'MEMBER', joinedAt: '2023-09-16T14:00:00Z', contributionXP: 350 },
      { userId: 'u7', userName: 'David Lee', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David', role: 'MEMBER', joinedAt: '2023-09-17T09:00:00Z', contributionXP: 420 },
    ],
    resources: [],
    challenges: ['c1', 'c2'],
    totalXP: 1270,
  },
  {
    id: 'sg2',
    name: 'Science Explorers',
    description: 'Exploring the wonders of science together',
    subject: 'Science',
    createdBy: 'u8',
    createdAt: '2023-09-20T11:00:00Z',
    members: [
      { userId: 'u8', userName: 'Olivia Martinez', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia', role: 'CREATOR', joinedAt: '2023-09-20T11:00:00Z', contributionXP: 600 },
      { userId: 'u9', userName: 'James Taylor', userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James', role: 'MEMBER', joinedAt: '2023-09-21T15:00:00Z', contributionXP: 450 },
    ],
    resources: [],
    challenges: ['c3'],
    totalXP: 1050,
  },
];

// Video Lessons Mock Data
export const MOCK_VIDEO_LESSONS: VideoLesson[] = [
  {
    id: 'v1',
    title: 'Introduction to Algebra',
    description: 'Learn the fundamentals of algebraic expressions and equations',
    subject: 'Math',
    videoUrl: 'https://example.com/video1.mp4',
    thumbnailUrl: 'https://via.placeholder.com/640x360',
    duration: 1800, // 30 minutes
    createdBy: 'u1',
    createdAt: '2023-10-01T10:00:00Z',
    xpReward: 100,
    quizzes: ['quiz1'],
    views: 245,
    likes: 32,
  },
  {
    id: 'v2',
    title: 'Photosynthesis Explained',
    description: 'Understanding how plants convert light into energy',
    subject: 'Science',
    videoUrl: 'https://example.com/video2.mp4',
    thumbnailUrl: 'https://via.placeholder.com/640x360',
    duration: 1200, // 20 minutes
    createdBy: 'u3',
    createdAt: '2023-10-05T09:00:00Z',
    xpReward: 80,
    views: 189,
    likes: 28,
  },
];

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: 'p1',
    name: 'Math Fundamentals',
    description: 'Complete guide to basic mathematics',
    createdBy: 'u1',
    videoIds: ['v1'],
    createdAt: '2023-10-01T10:00:00Z',
  },
];

// Notes & Study Materials Mock Data
export const MOCK_NOTES: Note[] = [
  {
    id: 'n1',
    title: 'Algebra Formulas Cheat Sheet',
    content: '# Algebra Formulas\n\n## Basic Formulas\n- Quadratic Formula: x = (-b ± √(b²-4ac)) / 2a\n- Slope: m = (y₂ - y₁) / (x₂ - x₁)',
    subject: 'Math',
    createdBy: 'u5',
    createdAt: '2023-10-01T10:00:00Z',
    updatedAt: '2023-10-05T14:00:00Z',
    isPublic: true,
    sharedWith: ['u6', 'u7'],
    tags: ['formulas', 'algebra', 'cheat-sheet'],
    collaborators: ['u6'],
  },
  {
    id: 'n2',
    title: 'Photosynthesis Notes',
    content: '# Photosynthesis\n\n## Process\n1. Light absorption\n2. Water splitting\n3. CO₂ fixation',
    subject: 'Science',
    createdBy: 'u8',
    createdAt: '2023-10-03T11:00:00Z',
    updatedAt: '2023-10-03T11:00:00Z',
    isPublic: false,
    sharedWith: ['u9'],
    tags: ['biology', 'photosynthesis'],
    collaborators: [],
  },
];

// Phase 3 Mock Data - Tournaments
export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: 'tour1',
    name: 'October Math Challenge',
    description: 'Compete in math quizzes and earn the highest score',
    type: 'MONTHLY',
    startDate: '2023-10-01T00:00:00Z',
    endDate: '2023-10-31T23:59:59Z',
    status: 'ACTIVE',
    prizePool: {
      first: 5000,
      second: 3000,
      third: 1000,
    },
    participants: ['team1', 'team2'],
    leaderboard: [
      { id: 'team1', name: 'Math Masters', score: 8500, rank: 1, progress: 85 },
      { id: 'team2', name: 'Science Squad', score: 7200, rank: 2, progress: 72 },
    ],
    rules: [
      'Complete at least 10 quizzes',
      'Highest total score wins',
      'No cheating allowed',
    ],
  },
];

// Peer Review Mock Data
export const MOCK_PEER_REVIEWS: PeerReview[] = [
  {
    id: 'pr1',
    taskId: 't1',
    taskTitle: 'Math Assignment: Quadratic Equations',
    reviewerId: 'u6',
    reviewerName: 'Emma Wilson',
    revieweeId: 'u5',
    revieweeName: 'Charlie Brown',
    submissionId: 'sub1',
    rating: 5,
    feedback: 'Excellent work! Your explanations are very clear and well-structured.',
    strengths: ['Clear explanations', 'Good use of examples', 'Neat presentation'],
    improvements: ['Could add more practice problems'],
    submittedAt: '2023-10-08T14:00:00Z',
    xpEarned: 50,
  },
];

// Flashcards Mock Data
export const MOCK_FLASHCARD_DECKS: FlashcardDeck[] = [
  {
    id: 'deck1',
    name: 'Algebra Formulas',
    description: 'Essential algebra formulas and equations',
    subject: 'Math',
    createdBy: 'u5',
    createdAt: '2023-10-01T10:00:00Z',
    isPublic: true,
    cardIds: ['fc1', 'fc2', 'fc3'],
    totalCards: 3,
    studyCount: 45,
  },
];

export const MOCK_FLASHCARDS: Flashcard[] = [
  {
    id: 'fc1',
    front: 'What is the quadratic formula?',
    back: 'x = (-b ± √(b²-4ac)) / 2a',
    subject: 'Math',
    tags: ['algebra', 'formula'],
    difficulty: 'MEDIUM',
    lastReviewed: '2023-10-08T10:00:00Z',
    nextReview: '2023-10-10T10:00:00Z',
    reviewCount: 5,
    correctCount: 4,
    masteryLevel: 80,
  },
  {
    id: 'fc2',
    front: 'What is photosynthesis?',
    back: 'The process by which plants convert light energy into chemical energy (glucose)',
    subject: 'Science',
    tags: ['biology', 'photosynthesis'],
    difficulty: 'EASY',
    lastReviewed: '2023-10-07T14:00:00Z',
    nextReview: '2023-10-09T14:00:00Z',
    reviewCount: 3,
    correctCount: 3,
    masteryLevel: 100,
  },
];

// Learning Analytics Mock Data
export const MOCK_WEAK_AREAS: WeakArea[] = [
  {
    subject: 'Math',
    topic: 'Calculus',
    score: 65,
    recommendation: 'Focus on practicing derivative problems',
    resources: ['v1', 'quiz1'],
  },
  {
    subject: 'Science',
    topic: 'Organic Chemistry',
    score: 70,
    recommendation: 'Review chemical bonding concepts',
    resources: ['v2'],
  },
];

// AI Features Mock Data
export const MOCK_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ai1',
    type: 'PREDICTION',
    title: 'Math Performance Expected to Improve',
    description: 'Based on recent engagement patterns, Math performance is predicted to increase by 12% in the next month. Students are showing increased activity in Math-related tasks.',
    confidence: 87,
    impact: 'HIGH',
    category: 'PERFORMANCE',
    timestamp: '2023-10-08T10:00:00Z',
    actionable: true,
    actionItems: ['Increase Math task difficulty', 'Add more Math challenges', 'Recognize top performers'],
    relatedData: {
      metric: 'Math Task Completion',
      value: 78,
      trend: 'UP',
    },
  },
  {
    id: 'ai2',
    type: 'RISK',
    title: '5 Students at Risk of Falling Behind',
    description: 'AI has identified 5 students showing declining engagement patterns. Early intervention recommended to prevent academic setbacks.',
    confidence: 92,
    impact: 'HIGH',
    category: 'ENGAGEMENT',
    timestamp: '2023-10-08T09:30:00Z',
    actionable: true,
    actionItems: ['Schedule one-on-one meetings', 'Assign mentor support', 'Create personalized learning plans'],
  },
  {
    id: 'ai3',
    type: 'OPPORTUNITY',
    title: 'High Engagement in Science Content',
    description: 'Science videos and quizzes are receiving 40% more engagement than average. Consider expanding Science content library.',
    confidence: 85,
    impact: 'MEDIUM',
    category: 'ENGAGEMENT',
    timestamp: '2023-10-08T08:15:00Z',
    actionable: true,
    actionItems: ['Add more Science video lessons', 'Create Science tournament', 'Feature Science achievements'],
    relatedData: {
      metric: 'Science Engagement',
      value: 140,
      trend: 'UP',
    },
  },
  {
    id: 'ai4',
    type: 'TREND',
    title: 'Gamification Elements Driving 25% More Participation',
    description: 'Students with active streaks and badges show 25% higher task completion rates. Gamification is proving highly effective.',
    confidence: 94,
    impact: 'HIGH',
    category: 'ENGAGEMENT',
    timestamp: '2023-10-07T16:00:00Z',
    actionable: true,
    actionItems: ['Introduce new badge categories', 'Create streak challenges', 'Enhance reward system'],
  },
  {
    id: 'ai5',
    type: 'RECOMMENDATION',
    title: 'Optimal Study Time Identified',
    description: 'AI analysis shows peak learning occurs between 2-4 PM. Consider scheduling important quizzes during this window.',
    confidence: 78,
    impact: 'MEDIUM',
    category: 'LEARNING',
    timestamp: '2023-10-07T14:00:00Z',
    actionable: true,
    actionItems: ['Schedule quizzes in afternoon', 'Send study reminders at optimal times'],
  },
];

export const MOCK_AI_PREDICTIONS: AIPrediction[] = [
  {
    id: 'pred1',
    target: 'Student Performance',
    prediction: 'Overall class performance expected to improve by 8% in next quarter',
    confidence: 82,
    timeframe: 'Next 30 days',
    factors: ['Increased engagement', 'Better attendance', 'Improved task completion'],
    recommendation: 'Maintain current teaching strategies and continue gamification efforts',
  },
  {
    id: 'pred2',
    target: 'Dropout Risk',
    prediction: 'Low risk of student dropouts (2% probability)',
    confidence: 91,
    timeframe: 'Next 90 days',
    factors: ['High engagement rates', 'Strong attendance', 'Positive social interactions'],
    recommendation: 'Continue monitoring but no immediate intervention needed',
  },
  {
    id: 'pred3',
    target: 'Subject Performance',
    prediction: 'History scores may decline by 5% if current trends continue',
    confidence: 75,
    timeframe: 'Next 30 days',
    factors: ['Lower engagement in History', 'Fewer History tasks completed', 'Reduced time spent on History'],
    recommendation: 'Increase History content variety and introduce interactive elements',
  },
];

export const MOCK_AI_RISK_ALERTS: AIRiskAlert[] = [
  {
    id: 'risk1',
    studentId: 'u5',
    studentName: 'Charlie Brown',
    riskType: 'ACADEMIC',
    severity: 'MEDIUM',
    description: 'Math scores have declined 15% over the past month. Student may need additional support.',
    indicators: ['Declining quiz scores', 'Reduced task completion', 'Lower engagement'],
    suggestedActions: ['Schedule tutoring session', 'Assign peer mentor', 'Provide additional resources'],
    detectedAt: '2023-10-08T10:00:00Z',
  },
  {
    id: 'risk2',
    studentId: 'u7',
    studentName: 'David Lee',
    riskType: 'ATTENDANCE',
    severity: 'HIGH',
    description: 'Attendance has dropped to 75% this month. Risk of falling behind.',
    indicators: ['Multiple absences', 'Missed assignments', 'No login activity'],
    suggestedActions: ['Contact parents', 'Schedule meeting', 'Create catch-up plan'],
    detectedAt: '2023-10-08T09:00:00Z',
  },
  {
    id: 'risk3',
    studentId: 'u9',
    studentName: 'James Taylor',
    riskType: 'ENGAGEMENT',
    severity: 'LOW',
    description: 'Engagement levels below average but stable. Monitor for changes.',
    indicators: ['Lower task participation', 'Reduced XP earning'],
    suggestedActions: ['Send encouragement message', 'Assign engaging tasks', 'Highlight achievements'],
    detectedAt: '2023-10-07T15:00:00Z',
  },
];

export const MOCK_AI_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: 'rec1',
    title: 'Implement Adaptive Learning Paths',
    description: 'AI suggests creating personalized learning paths for students based on their performance data. This could improve outcomes by 20%.',
    category: 'CURRICULUM',
    priority: 'HIGH',
    estimatedImpact: '20% improvement in student outcomes',
    implementationEffort: 'MEDIUM',
    relatedInsights: ['ai1', 'ai4'],
  },
  {
    id: 'rec2',
    title: 'Early Intervention Program',
    description: 'Establish an early intervention program for at-risk students. AI predicts this could reduce dropout rates by 30%.',
    category: 'INTERVENTION',
    priority: 'HIGH',
    estimatedImpact: '30% reduction in dropout risk',
    implementationEffort: 'HIGH',
    relatedInsights: ['ai2'],
  },
  {
    id: 'rec3',
    title: 'Expand Science Content',
    description: 'Given high engagement in Science content, consider adding more interactive Science modules and resources.',
    category: 'RESOURCE',
    priority: 'MEDIUM',
    estimatedImpact: '15% increase in Science performance',
    implementationEffort: 'LOW',
    relatedInsights: ['ai3'],
  },
];

