import type { User, Task, LeaderboardEntry, Reward, Student, Class, PerformanceData, Notification } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Alice Teacher',
    email: 'alice@school.com',
    role: 'TEACHER',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
  },
  {
    id: 'u2',
    name: 'Bob Admin',
    email: 'admin@school.com',
    role: 'ADMIN',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
  },
  {
    id: 'u3',
    name: 'Sarah Johnson',
    email: 'sarah@school.com',
    role: 'TEACHER',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  },
  {
    id: 'u4',
    name: 'Michael Chen',
    email: 'michael@school.com',
    role: 'TEACHER',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
  },
  {
    id: 's1',
    name: 'Charlie Student',
    email: 'charlie@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie',
    grade: '10',
    section: 'A',
    xp: 1250,
    wallet: 300,
  } as Student,
  {
    id: 's2',
    name: 'Diana Prince',
    email: 'diana@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diana',
    grade: '10',
    section: 'A',
    xp: 1200,
    wallet: 250,
  } as Student,
  {
    id: 's3',
    name: 'Clark Kent',
    email: 'clark@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Clark',
    grade: '10',
    section: 'B',
    xp: 1150,
    wallet: 200,
  } as Student,
  {
    id: 's4',
    name: 'Bruce Wayne',
    email: 'bruce@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bruce',
    grade: '10',
    section: 'A',
    xp: 1100,
    wallet: 180,
  } as Student,
  {
    id: 's5',
    name: 'Peter Parker',
    email: 'peter@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Peter',
    grade: '9',
    section: 'A',
    xp: 1050,
    wallet: 150,
  } as Student,
  {
    id: 's6',
    name: 'Emma Watson',
    email: 'emma@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    grade: '10',
    section: 'B',
    xp: 1020,
    wallet: 140,
  } as Student,
  {
    id: 's7',
    name: 'James Bond',
    email: 'james@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    grade: '9',
    section: 'B',
    xp: 980,
    wallet: 120,
  } as Student,
  {
    id: 's8',
    name: 'Natasha Romanoff',
    email: 'natasha@school.com',
    role: 'STUDENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Natasha',
    grade: '10',
    section: 'A',
    xp: 950,
    wallet: 110,
  } as Student,
  {
    id: 'p1',
    name: 'David Parent',
    email: 'david@parent.com',
    role: 'PARENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
  },
  {
    id: 'p2',
    name: 'Maria Garcia',
    email: 'maria@parent.com',
    role: 'PARENT',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
  },
];

export const MOCK_CLASSES: Class[] = [
  { id: 'c1', name: 'Grade 10A', grade: '10', section: 'A', teacherId: 'u1', studentCount: 28 },
  { id: 'c2', name: 'Grade 10B', grade: '10', section: 'B', teacherId: 'u1', studentCount: 25 },
  { id: 'c3', name: 'Grade 9A', grade: '9', section: 'A', teacherId: 'u3', studentCount: 30 },
  { id: 'c4', name: 'Grade 9B', grade: '9', section: 'B', teacherId: 'u3', studentCount: 27 },
  { id: 'c5', name: 'Grade 11A', grade: '11', section: 'A', teacherId: 'u4', studentCount: 32 },
  { id: 'c6', name: 'Grade 11B', grade: '11', section: 'B', teacherId: 'u4', studentCount: 29 },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Algebra Linear Equations',
    description: 'Complete exercises 5.1 to 5.5 in your textbook. Show all work and submit your solutions.',
    subject: 'Math',
    assignedDate: '2023-10-01',
    dueDate: '2023-10-10',
    xpReward: 100,
    status: 'PENDING',
  },
  {
    id: 't2',
    title: 'Physics Lab Report',
    description: 'Submit the lab report for the Pendulum experiment. Include data analysis and conclusions.',
    subject: 'Science',
    assignedDate: '2023-10-02',
    dueDate: '2023-10-09',
    xpReward: 150,
    status: 'SUBMITTED',
    submittedFileUrl: 'http://example.com/report.pdf',
  },
  {
    id: 't3',
    title: 'History Essay',
    description: 'Write an essay on the Industrial Revolution (500-700 words). Include causes, effects, and historical significance.',
    subject: 'History',
    assignedDate: '2023-09-20',
    dueDate: '2023-09-30',
    xpReward: 200,
    status: 'GRADED',
    grade: 'A',
    feedback: 'Excellent work! Well-researched and clearly written.',
  },
  {
    id: 't4',
    title: 'English Poetry Analysis',
    description: 'Analyze the poem "The Road Not Taken" by Robert Frost. Discuss themes, literary devices, and personal interpretation.',
    subject: 'English',
    assignedDate: '2023-10-05',
    dueDate: '2023-10-12',
    xpReward: 120,
    status: 'PENDING',
  },
  {
    id: 't5',
    title: 'Chemistry Periodic Table Quiz',
    description: 'Complete the online quiz on periodic table trends and element properties.',
    subject: 'Science',
    assignedDate: '2023-10-03',
    dueDate: '2023-10-08',
    xpReward: 80,
    status: 'SUBMITTED',
    submittedFileUrl: 'http://example.com/quiz.pdf',
  },
  {
    id: 't6',
    title: 'Geometry Problem Set',
    description: 'Solve problems 1-15 from Chapter 7. Focus on triangle properties and proofs.',
    subject: 'Math',
    assignedDate: '2023-09-25',
    dueDate: '2023-10-05',
    xpReward: 110,
    status: 'GRADED',
    grade: 'B+',
    feedback: 'Good effort! Review triangle congruence theorems.',
  },
  {
    id: 't7',
    title: 'World War II Presentation',
    description: 'Create a 10-slide presentation on a major battle of WWII. Include images and citations.',
    subject: 'History',
    assignedDate: '2023-10-06',
    dueDate: '2023-10-15',
    xpReward: 180,
    status: 'PENDING',
  },
  {
    id: 't8',
    title: 'Biology Cell Structure Lab',
    description: 'Complete the microscope lab worksheet on plant and animal cell structures.',
    subject: 'Science',
    assignedDate: '2023-10-04',
    dueDate: '2023-10-11',
    xpReward: 90,
    status: 'SUBMITTED',
    submittedFileUrl: 'http://example.com/lab.pdf',
  },
  {
    id: 't9',
    title: 'Creative Writing Assignment',
    description: 'Write a short story (1000 words) with a clear plot, setting, and character development.',
    subject: 'English',
    assignedDate: '2023-09-28',
    dueDate: '2023-10-07',
    xpReward: 140,
    status: 'GRADED',
    grade: 'A-',
    feedback: 'Creative and engaging! Work on dialogue formatting.',
  },
  {
    id: 't10',
    title: 'Calculus Derivatives Practice',
    description: 'Complete the derivative practice problems. Show all steps in your solutions.',
    subject: 'Math',
    assignedDate: '2023-10-07',
    dueDate: '2023-10-14',
    xpReward: 130,
    status: 'PENDING',
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, studentId: 's1', studentName: 'Charlie Student', xp: 1250, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie' },
  { rank: 2, studentId: 's2', studentName: 'Diana Prince', xp: 1200, trend: 'SAME', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diana' },
  { rank: 3, studentId: 's3', studentName: 'Clark Kent', xp: 1150, trend: 'DOWN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Clark' },
  { rank: 4, studentId: 's4', studentName: 'Bruce Wayne', xp: 1100, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bruce' },
  { rank: 5, studentId: 's5', studentName: 'Peter Parker', xp: 1050, trend: 'SAME', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Peter' },
  { rank: 6, studentId: 's6', studentName: 'Emma Watson', xp: 1020, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma' },
  { rank: 7, studentId: 's7', studentName: 'James Bond', xp: 980, trend: 'DOWN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James' },
  { rank: 8, studentId: 's8', studentName: 'Natasha Romanoff', xp: 950, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Natasha' },
  { rank: 9, studentId: 's9', studentName: 'Tony Stark', xp: 920, trend: 'SAME', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tony' },
  { rank: 10, studentId: 's10', studentName: 'Steve Rogers', xp: 890, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Steve' },
  { rank: 11, studentId: 's11', studentName: 'Wanda Maximoff', xp: 870, trend: 'DOWN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Wanda' },
  { rank: 12, studentId: 's12', studentName: 'Barry Allen', xp: 850, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Barry' },
  { rank: 13, studentId: 's13', studentName: 'Oliver Queen', xp: 820, trend: 'SAME', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver' },
  { rank: 14, studentId: 's14', studentName: 'Kara Danvers', xp: 800, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kara' },
  { rank: 15, studentId: 's15', studentName: 'John Constantine', xp: 780, trend: 'DOWN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John' },
  { rank: 16, studentId: 's16', studentName: 'Zatanna Zatara', xp: 760, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Zatanna' },
  { rank: 17, studentId: 's17', studentName: 'Arthur Curry', xp: 740, trend: 'SAME', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arthur' },
  { rank: 18, studentId: 's18', studentName: 'Diana Prince', xp: 720, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diana2' },
  { rank: 19, studentId: 's19', studentName: 'Hal Jordan', xp: 700, trend: 'DOWN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hal' },
  { rank: 20, studentId: 's20', studentName: 'Jessica Cruz', xp: 680, trend: 'UP', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica' },
];

export const MOCK_REWARDS: Reward[] = [
  { id: 'r1', name: 'Homework Pass', cost: 500, type: 'PRIVILEGE' },
  { id: 'r2', name: 'Extra 5 mins Break', cost: 200, type: 'PRIVILEGE' },
  { id: 'r3', name: 'Fancy Pen', cost: 1000, type: 'ITEM' },
  { id: 'r4', name: 'Lunch with Teacher', cost: 800, type: 'PRIVILEGE' },
  { id: 'r5', name: 'Custom Notebook', cost: 600, type: 'ITEM' },
  { id: 'r6', name: 'Skip One Quiz', cost: 400, type: 'PRIVILEGE' },
  { id: 'r7', name: 'School Merchandise', cost: 1200, type: 'ITEM' },
  { id: 'r8', name: 'Extra Credit Opportunity', cost: 300, type: 'PRIVILEGE' },
  { id: 'r9', name: 'Gift Card ($10)', cost: 1500, type: 'ITEM' },
  { id: 'r10', name: 'Choose Your Seat', cost: 250, type: 'PRIVILEGE' },
];

export const MOCK_PERFORMANCE: PerformanceData[] = [
  // Math
  { subject: 'Math', score: 95, date: '2023-09-01', xpEarned: 100 },
  { subject: 'Math', score: 92, date: '2023-09-15', xpEarned: 95 },
  { subject: 'Math', score: 98, date: '2023-10-01', xpEarned: 105 },
  { subject: 'Math', score: 94, date: '2023-10-15', xpEarned: 100 },
  { subject: 'Math', score: 96, date: '2023-11-01', xpEarned: 102 },
  // Science
  { subject: 'Science', score: 88, date: '2023-09-05', xpEarned: 90 },
  { subject: 'Science', score: 90, date: '2023-09-20', xpEarned: 92 },
  { subject: 'Science', score: 93, date: '2023-10-05', xpEarned: 95 },
  { subject: 'Science', score: 91, date: '2023-10-20', xpEarned: 93 },
  { subject: 'Science', score: 95, date: '2023-11-05', xpEarned: 98 },
  // History
  { subject: 'History', score: 85, date: '2023-09-10', xpEarned: 85 },
  { subject: 'History', score: 90, date: '2023-09-25', xpEarned: 90 },
  { subject: 'History', score: 87, date: '2023-10-10', xpEarned: 87 },
  { subject: 'History', score: 92, date: '2023-10-25', xpEarned: 92 },
  // English
  { subject: 'English', score: 89, date: '2023-09-08', xpEarned: 89 },
  { subject: 'English', score: 91, date: '2023-09-22', xpEarned: 91 },
  { subject: 'English', score: 88, date: '2023-10-08', xpEarned: 88 },
  { subject: 'English', score: 93, date: '2023-10-22', xpEarned: 93 },
  { subject: 'English', score: 90, date: '2023-11-08', xpEarned: 90 },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', title: 'New Task Assigned', message: 'You have a new Math assignment due tomorrow', type: 'INFO', read: false, timestamp: '2023-10-08T10:00:00Z' },
  { id: 'n2', title: 'Task Graded', message: 'Your History essay has been graded: A', type: 'SUCCESS', read: false, timestamp: '2023-10-07T14:30:00Z' },
  { id: 'n3', title: 'XP Earned', message: 'You earned 150 XP for completing Physics Lab', type: 'SUCCESS', read: true, timestamp: '2023-10-06T09:15:00Z' },
  { id: 'n4', title: 'Leaderboard Update', message: 'You moved up to #1 position!', type: 'SUCCESS', read: false, timestamp: '2023-10-05T16:45:00Z' },
  { id: 'n5', title: 'Reward Available', message: 'New reward "Homework Pass" is now available in the store', type: 'INFO', read: false, timestamp: '2023-10-04T11:20:00Z' },
  { id: 'n6', title: 'Task Reminder', message: 'Your English assignment is due in 2 days', type: 'WARNING', read: true, timestamp: '2023-10-03T08:30:00Z' },
  { id: 'n7', title: 'Achievement Unlocked', message: 'Congratulations! You completed 10 tasks this month', type: 'SUCCESS', read: true, timestamp: '2023-10-02T15:00:00Z' },
  { id: 'n8', title: 'Task Graded', message: 'Your Math quiz has been graded: B+', type: 'SUCCESS', read: false, timestamp: '2023-10-01T12:00:00Z' },
  { id: 'n9', title: 'XP Milestone', message: 'You reached 1000 XP! Level up!', type: 'SUCCESS', read: true, timestamp: '2023-09-30T10:00:00Z' },
  { id: 'n10', title: 'New Task Assigned', message: 'Chemistry lab report due next week', type: 'INFO', read: false, timestamp: '2023-09-29T14:15:00Z' },
];

